/**
 * CCLD inference tests (feat/claudish M5).
 *
 * Parity: the committed fixtures were generated by the trainer through
 * the SHIPPED forward pass on the QUANTIZED tensors — replaying them
 * here proves load → dequantize → forward reproduces training-time
 * outputs. Size caps pin the "few tens of KB" contract. A configHash
 * mismatch must refuse the model (heuristic fallback), never serve
 * garbage probabilities.
 */
import { statSync } from 'node:fs';
import path from 'node:path';

import {
  loadCcldModel,
  resetCcldForTests,
  warmCcld,
  isCcldAvailable,
  getCcldModel,
} from '@/lib/claudish/ccld';
import { probabilityClaudish } from '@/lib/claudish/ccld-inference';
import fixtures from '@/lib/claudish/ccld-fixtures.json';
import weights from '@/lib/claudish/ccld-weights.json';

describe('weights artifact', () => {
  it('stays within the size contract (8KB floor catches truncation, 64KB cap)', () => {
    const bytes = statSync(
      path.join(process.cwd(), 'src', 'lib', 'claudish', 'ccld-weights.json'),
    ).size;
    expect(bytes).toBeGreaterThan(8 * 1024);
    expect(bytes).toBeLessThan(64 * 1024);
  });

  it('loads as a version-1 model', () => {
    expect(loadCcldModel(weights)).not.toBeNull();
  });
});

describe('fixture parity (training-time outputs replayed through the shipped path)', () => {
  const model = loadCcldModel(weights);

  it.each(
    (fixtures.inferenceCases as Array<{ text: string; p: number }>).map((c) => [
      c.text.slice(0, 30) || '(empty)',
      c,
    ]),
  )('reproduces p for %s', (_label, testCase) => {
    expect(model).not.toBeNull();
    const p = (model as NonNullable<typeof model>).predict((testCase as { text: string }).text);
    expect(p).toBeCloseTo((testCase as { p: number }).p, 5);
  });

  it('classifies the canonical pair, and no longer leans on terse imperatives', () => {
    const m = model as NonNullable<typeof model>;
    expect(
      m.predict(
        "This isn't just a refactor — it's a robust, seamless transformation, underscoring everything.",
      ),
    ).toBeGreaterThan(0.8);
    expect(m.predict('lol yeah that is broken, been meaning to fix it for weeks tbh')).toBeLessThan(
      0.2,
    );
    // The first trained model leaned Claudish (~0.72) on terse workplace
    // imperatives; the conversational negative sources (movie dialogs,
    // 1990s usenet) taught it that humans talk like this. Pinned English.
    expect(m.predict('The meeting moved to Thursday. Bring the numbers.')).toBeLessThan(0.5);
  });
});

describe('configHash refusal', () => {
  it('refuses weights trained against a different featurizer', () => {
    const tampered = JSON.parse(JSON.stringify(weights)) as {
      featurizer: { configHash: string };
    };
    tampered.featurizer.configHash = 'deadbeef'.repeat(8);
    expect(loadCcldModel(tampered)).toBeNull();
  });

  it('refuses unknown versions and junk', () => {
    expect(loadCcldModel({ version: 2 })).toBeNull();
    expect(loadCcldModel(null)).toBeNull();
    expect(loadCcldModel('weights')).toBeNull();
  });
});

describe('warm-up', () => {
  it('makes the model available after warmCcld with the trained weights', async () => {
    resetCcldForTests();
    expect(isCcldAvailable()).toBe(false);
    await warmCcld();
    expect(isCcldAvailable()).toBe(true);
    expect(getCcldModel()?.predict(' — not just a test; a testament —')).toBeGreaterThan(0.5);
  });

  it('serves rule F: the mean of the register weights and the shape weights (dev trial 2026-09-02)', async () => {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const shape = require('@/lib/claudish/ccld-weights-shape.json');
    const register = loadCcldModel(weights)!;
    const shapeModel = loadCcldModel(shape)!;
    resetCcldForTests();
    await warmCcld();
    const served = getCcldModel()!;
    // A structural Claude reply: the register model reads it plain, the shape model reads it Claude; F averages.
    const text =
      "Two caveats I'll carry rather than bury. The join failing is weak evidence on its own; the absent capture is the strong part.";
    expect(served.predict(text)).toBeCloseTo(
      (register.predict(text) + shapeModel.predict(text)) / 2,
      9,
    );
    expect(shapeModel.predict(text)).toBeGreaterThan(register.predict(text));
  });

  it('keeps the shape weights inside the same size budget as the primary file', () => {
    const bytes = statSync(
      path.join(process.cwd(), 'src', 'lib', 'claudish', 'ccld-weights-shape.json'),
    ).size;
    expect(bytes).toBeLessThanOrEqual(64 * 1024);
  });
});

describe('temperature scaling', () => {
  it('probabilityClaudish is monotone in the logit gap', () => {
    expect(probabilityClaudish([0, 2], 1.2)).toBeGreaterThan(probabilityClaudish([0, 1], 1.2));
    expect(probabilityClaudish([1, 1], 1.2)).toBeCloseTo(0.5, 10);
  });

  it('forwardLogits handles empty features', () => {
    const model = loadCcldModel(weights);
    expect(model?.predict('')).toBeGreaterThanOrEqual(0);
  });
});

describe('blessed-config loading (v2 mask models)', () => {
  it('accepts weights stamped with the v2 configHash', () => {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { loadCcldModel } = require('@/lib/claudish/ccld');
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { CCLD_V2_CONFIG, configHash } = require('@/lib/claudish/ccld-featurizer');
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const shipped = require('@/lib/claudish/ccld-weights.json');
    const v2 = JSON.parse(JSON.stringify(shipped));
    v2.featurizer = { ...CCLD_V2_CONFIG, configHash: configHash(CCLD_V2_CONFIG) };
    const model = loadCcldModel(v2);
    expect(model).not.toBeNull();
    expect(model!.predict('hello world')).toBeGreaterThanOrEqual(0);
  });

  it('still refuses an unknown configHash', () => {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { loadCcldModel } = require('@/lib/claudish/ccld');
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const shipped = require('@/lib/claudish/ccld-weights.json');
    const tampered = JSON.parse(JSON.stringify(shipped));
    tampered.featurizer.configHash = 'f'.repeat(64);
    expect(loadCcldModel(tampered)).toBeNull();
  });
});
